# Database credentials
DB_HOST = "db.eebexeqcghbjbvwamuki.supabase.co"
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASS = "INCUzikmMETFVAKe"
DB_PORT = 5432

# Optional: Fernet encryption key for extra security
FERNET_KEY = "YOUR-FERNET-KEY"  # generate using Fernet.generate_key().decode()
